config/routes.rb
Tabbo::Application.routes.draw do

  resources :tabs

end

app/models/tab.rb
class Tab < ActiveRecord::Base
  INSTRUMENTS = %W[ guitar 7string-guitar bass 5string-bass mandolin 4string-bouzouki 3string-bouzouki ]
  
  before_save :default_values
  before_validation :set_content
  validates :title, :content, presence: true, uniqueness: true, allow_nil: false
  attr_accessible :title, :content, :instrument
  
  def has_user?
    self.user_id == 0 ? false : true
  end
  
  
=begin rdoc
  Return an old-style text-only tab
=end
  def to_text
    text = "#{title.center(fretboard.first.size)}\n"
    text << fretboard.join("\n")
  end
  
  def to_page width = 80
    if fretboard.first.size > width
      fixed_length_fretboard = fretboard.map do |string|
        string.scan(/.{1,#{width}}/)
      end
      page = "#{title.center(width)}\n"
      data = (0..(fixed_length_fretboard.first.size-1)).map { |row| fixed_length_fretboard.map {|string| string[row]} }
      page << data.map {|row| row.map {|r| r.ljust(width,'-')}.join("\n")}.join("\n\n")
    else
      to_text
    end
  end
  
=begin rdoc
  returns an array representing a fretboard. Right now time is not represented, only finger positions on strings
=end
  def fretboard
    return @fretboard if @fretboard.present? and !self.content_changed?
    fretboard = (1..string_count).collect {(1..tab_length).collect { "---" }}
    
    vertical_count = 0
    verticals.each do |strum|
      
      if strum.first.is_a?(Integer)
        if strum == [0] # it's a pause
          fretboard[0][vertical_count] = '---'
        else # it's a single note
          string, fret = strum
          fretboard[string-1][vertical_count] = fret >= 10 ? "#{fret}-" : "#{fret}--"
        
        end
      # it's a chord
      else
        strum.each do |note|
          begin
            string, fret = note
            fretboard[string-1][vertical_count] = fret >= 10 ? "#{fret}-" : "#{fret}--"
          rescue Exception => e
            raise 'Error parsing ' + note.inspect
          end
          
          
        end
      end
      vertical_count += 1
    end
    @fretboard = fretboard.map(&:join).reverse
  end
  
  def tab_length
    verticals.size
  end
  
  def string_count
    case self.instrument
    when '7string-guitar'
      7
    when 'guitar'
      6
    when '5string-bass'
      5
    when 'mandolin', '4string-bouzouki', 'bass'
      4
    when '3string-bouzouki'
      3
    end
  end
  
  def verticals
    JSON.parse(content)
  end
protected
  def default_values
    self.instrument = 'guitar' if self.instrument.blank?
  end
  
  def set_content
    if(JSON.parse(self.content).uniq.flatten.empty?)
      self.content = nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  before_filter :set_session_browser
  
  def set_session_browser
    unless session[:browser]
      user_agent = request.env['HTTP_USER_AGENT'].to_s.downcase
      session[:browser] = if user_agent =~ /msie/i
        "ie"
      elsif user_agent =~ /konqueror/i
        "konqueror"
      elsif user_agent =~ /opera/i
        "opera"
      elsif user_agent =~ /chrome/i
        "chrome"
      elsif user_agent =~ /applewebkit/i
        "safari"
      elsif user_agent =~ /gecko/i
        "firefox"
      else
        "unknown"
      end
    end
  end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  before_filter :load_tab, only: [:show, :edit, :update]
  def new
    @tab = Tab.new(instrument: 'guitar')
  end
  
  def create
    @tab = Tab.new(params[:tab])
    if @tab.save
      redirect_to tab_path(@tab)
    else
      flash[:error] = 'Curses! Curses? Yah. Something went wrong'
      render :new
    end
  end
  
  def edit
    render :new
  end
  
  def update
    if @tab.update_attributes(params[:tab])
      redirect_to tab_path(@tab)
    else
      flash[:error] = 'Curses! Curses? Yah. Something went wrong'
      render :edit
    end
    
  end
  
  def show
  end

protected
  def load_tab
    @tab = Tab.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    "#{controller.controller_name} #{controller.action_name} #{session[:browser]}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabbo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">

<% flash.each do |name, msg| %>
  <div class="flash-message <%= name %>">
    <a href="#" class="close">close</a>
    <p><%= msg %></p>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/tabs/new.html.erb
<%= form_for @tab do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :content %>
  <p><%= f.text_field :title, :placeholder => 'Title' %></p>
  <p class="instruments">
    <% Tab::INSTRUMENTS.each do |instrument| %>
      <label for="tab_instrument_<%= instrument %>"><%= instrument.capitalize %>
      <%= f.radio_button :instrument, instrument %></label>
    <% end %>
  </p>
  <div class="row fretboard">
  <% (1..30).each do |grid| %>
    <ul class="grid1 column v<%= grid %>" data-vertical="<%= grid %>">
      <% (1..@tab.string_count).to_a.reverse.each do |string| %>
        <li class="s<%= string %>" data-string="<%= string %>">
          <div id="g<%= grid %>_<%= string %>"></div>
        </li>
      <% end %>
    </ul>
  <% end %>
  </div>
  <p><%= f.submit %></p>
<% end %>

<% if @tab.content.present? %>
<script>
var content = <%= JSON.parse(@tab.content) %>;
for (var x = 0; x < content.length; x++) {
  for (var y = 0; y < content[x].length; y++) {
    data = content[x][y];
    $('.fretboard ul[data-vertical="'+(x+1)+'"] li[data-string="'+data[0]+'"] div').text(data[1]);
  };
};
</script>
<% end %>

app/views/tabs/show.html.erb
<pre><%= @tab.to_page(120) %></pre>
<%= link_to 'edit', edit_tab_path(@tab) %>